
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/quesbank?serverTimezone=UTC&characterEncoding=utf8
  profiles: dev
  redis:
    host: 192.168.23.160
    timeout: 30000
#  rabbitmq:
#    host: 192.168.23.160
#    password: guest
#    username: guest
#    port: 5672
server:
  port: 8000