
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/quesbank?serverTimezone=UTC&characterEncoding=utf8
  profiles: dev
  data:
    elasticsearch:
      cluster-nodes: 192.168.23.160:9300
      cluster-name: my-es
server:
  port: 8001